insert into movies (movie_id, title, genre, description) values
(1, 'Hotel for Dogs', 'Adventure|Children|Comedy', 'An adventure about two kids who secretly shelter dogs in an abandoned hotel.'),
(2, 'Raja', 'Drama', 'A heartfelt drama that delves into the life and challenges of a character named Raja.'),
(3, 'Gymnast, The', 'Drama|Romance', 'A story of passion and romance in the competitive world of gymnastics.'),
(4, 'Terror Beneath the Sea, The (Kaitei daisensô)', 'Action|Sci-Fi', 'A sci-fi adventure involving mysterious creatures in the depths of the ocean.'),
(5, 'Tomorrow Never Dies', 'Action|Adventure|Thriller', 'An action-packed spy thriller with high-stakes global intrigue.'),
(6, 'Assassination (Ansatsu)', 'Action|Drama', 'A gripping tale of political conspiracy and an assassination plot.'),
(7, 'September', 'Drama', 'A drama filled with emotional twists and turns set in the autumn month.'),
(8, 'Carrie', 'Drama|Horror', 'A chilling horror story about a young girl with telekinetic powers.'),
(9, 'Ninja Assassin', 'Action|Crime|Drama|Thriller', 'A fast-paced thriller about a ninja confronting a dark criminal world.'),
(10, 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les)', 'Drama|Musical|Romance', 'A visually stunning musical set in Cherbourg, exploring young love.'),
(11, 'Camille Claudel 1915', 'Drama', 'A biographical drama about the life and struggles of artist Camille Claudel.'),
(12, 'Hellraiser: Hellseeker', 'Horror', 'A horror film delving into a world of nightmares and dark fantasies.'),
(13, 'History of Future Folk, The', 'Adventure|Comedy|Musical|Sci-Fi', 'A sci-fi comedy about musicians from the future navigating Earth.'),
(14, 'Let the Good Times Roll', 'Documentary', 'A nostalgic documentary celebrating the early years of rock and roll.'),
(15, 'Crossing Over', 'Drama', 'An intimate look at the lives and stories of immigrants.'),
(16, 'Why Be Good?', 'Comedy|Romance', 'A lighthearted romantic comedy set in the roaring 20s.'),
(17, 'Alphaville (Alphaville, une étrange aventure de Lemmy Caution)', 'Drama|Mystery|Romance|Sci-Fi|Thriller', 'A futuristic thriller blending mystery and romance in a dystopian city.'),
(18, 'Revenge of the Green Dragons', 'Action|Crime|Drama', 'An action-packed drama about two brothers in New York''s underworld.'),
(19, 'Sands of Iwo Jima', 'Action|Drama|Romance|War', 'A war drama portraying the Battle of Iwo Jima and its heroes.'),
(20, 'Twice Upon a Yesterday (a.k.a. Man with Rain in His Shoes, The)', 'Comedy|Drama|Romance', 'A romantic comedy about getting a second chance to fix past mistakes.'),
(21, 'Whity', 'Drama|Western', 'A complex tale set in the American West, focusing on a multiracial family''s dynamics.'),
(22, 'Last Sunset, The', 'Western', 'A gripping Western featuring a showdown between a lawman and a fugitive.'),
(23, 'Fallen Art (Sztuka spadania)', 'Action|Animation|Comedy', 'An animated tale blending action and comedy with a unique artistic style.'),
(24, 'Three Marias, The (Três Marias, As)', 'Drama', 'A dramatic story of three women bound by a shared quest for justice.'),
(25, 'Getting Any? (Minnâ-yatteruka!)', 'Comedy', 'A comedic journey of a man''s desperate attempts to understand love and relationships.'),
(26, 'Salla: Selling the Silence', 'Documentary', 'An insightful documentary exploring the concept and value of silence.'),
(27, 'Windfall', 'Documentary', 'A documentary delving into the complexities and controversies of wind energy.'),
(28, 'Sisterhood of the Traveling Pants, The', 'Adventure|Comedy|Drama', 'A heartwarming story about friendship and life changes, symbolized by a pair of jeans.'),
(29, 'Super Rich: The Greed Game', 'Documentary', 'An exploration into the lives and motivations of the super-wealthy.'),
(30, 'Touch the Top of the World', 'Drama', 'An inspiring drama about overcoming physical limitations to achieve extraordinary goals.'),
(31, '10th & Wolf', 'Crime|Drama|Thriller', 'A gritty thriller set in the underworld of Philadelphia.'),
(32, 'Lupin III: The Castle Of Cagliostro', 'Action|Adventure|Animation|Comedy|Crime|Mystery', 'An animated adventure of a master thief uncovering a royal conspiracy.'),
(33, 'Lap Dance', 'Drama', 'A dramatic tale of a woman''s journey into the world of exotic dancing to support her family.'),
(34, 'Air Guitar Nation', 'Comedy|Documentary|Musical', 'A humorous documentary exploring the competitive world of air guitar championships.'),
(35, 'Naked Lunch', 'Drama|Fantasy|Mystery|Sci-Fi', 'A surreal journey through a writer''s hallucinations and bizarre experiences.'),
(36, 'Novena, The (La neuvaine)', 'Drama', 'A powerful drama about faith, healing, and unexpected friendship.'),
(37, 'The Case of the Scorpion''s Tail', 'Mystery|Thriller', 'A thrilling mystery involving a deadly inheritance and a series of murders.'),
(38, 'Born to Dance', 'Comedy|Musical', 'A lively musical about aspiring dancers chasing their dreams.'),
(39, 'Boys from Brazil, The', 'Action|Mystery|Thriller', 'A thrilling tale of a Nazi hunter uncovering a sinister plot in South America.'),
(40, 'Captain''s Paradise, The', 'Comedy', 'A comedic story of a ship captain juggling relationships in two ports.'),
(41, 'Stations of the Cross', 'Drama', 'A dramatic portrayal of a young girl''s religious devotion and struggle.'),
(42, 'House of Wax', 'Horror|Thriller', 'A chilling horror about a group of friends trapped in a sinister wax museum.'),
(43, 'Puppet Master II', 'Horror|Sci-Fi|Thriller', 'A horror sequel with evil puppets coming to life.'),
(44, 'Sweet Liberty', 'Comedy', 'A light-hearted comedy about the chaotic making of a historical film.'),
(45, 'That Lady in Ermine', 'Comedy|Fantasy|Musical|Romance', 'A romantic comedy mixed with fantasy and musical elements.'),
(46, 'Now and Forever', 'Drama|Romance', 'A timeless romance drama about enduring love through hardships.'),
(47, 'Volcano High (Whasango)', 'Action|Comedy', 'A high-energy action comedy set in a school with supernatural events.'),
(48, 'Christmas on Mars', 'Sci-Fi', 'A sci-fi adventure unfolding the mysteries of Mars during Christmas.'),
(49, 'God''s Pocket', 'Drama', 'A gripping drama about the dark secrets of a blue-collar neighborhood.'),
(50, 'Last Laugh, The (Letzte Mann, Der)', 'Drama', 'A classic drama depicting the fall and redemption of a proud doorman.'),
(51, 'Verlorene, Der (Lost One, The)', 'Crime|Drama|Thriller', 'A crime thriller about a man confronting his war-time past.'),
(52, 'Aliens of the Deep', 'Documentary|IMAX', 'A visually stunning documentary exploring the depths of Earth''s oceans.'),
(53, 'Subject Two', 'Drama|Thriller', 'A thrilling drama about a medical student involved in ethically dubious experiments.'),
(54, 'Out of Bounds', 'Drama', 'A drama about a young man''s struggle to escape his troubled urban life.'),
(55, 'Eragon', 'Action|Adventure|Fantasy', 'A fantastical adventure of a young farm boy who discovers a dragon''s egg.'),
(56, 'Fire Within, The (Feu follet, Le)', 'Drama', 'An intense drama about a man grappling with existential crises.'),
(57, 'Jackboots on Whitehall', 'Animation|Comedy|Sci-Fi|War', 'An animated comedy spoofing WWII with an alternate history twist.'),
(58, 'Devil Hunter (El caníbal)', 'Horror', 'A horror adventure set in a jungle with a terrifying cannibal.'),
(59, 'How to Lose Friends & Alienate People', 'Comedy', 'A comedy about a bumbling journalist trying to fit into the high-profile world of media.'),
(60, 'Date and Switch', 'Comedy', 'A light-hearted comedy about two friends dealing with unexpected romantic situations.'),
(61, 'One Hour with You', 'Comedy|Musical|Romance', 'A musical romance filled with comedic misunderstandings and affairs.'),
(62, 'Sum of All Fears, The', 'Drama|Thriller', 'A political thriller about a nuclear crisis threatening world peace.'),
(63, 'Dominick and Eugene', 'Drama', 'A heartwarming story of two brothers and their unbreakable bond.'),
(64, 'Kummeli Alivuokralainen', 'Comedy', 'A Finnish comedy about the hilarious antics of quirky tenants.'),
(65, 'Rebecca', 'Drama|Mystery|Romance|Thriller', 'A romantic thriller about a young bride haunted by her husband''s mysterious past.'),
(66, 'Children of the Secret State', 'Documentary', 'A documentary exposing the harsh realities of life in North Korea.'),
(67, 'Godfather, The', 'Crime|Drama', 'An epic crime drama about a powerful mafia family and their complex dynamics.'),
(68, 'Panic Button', 'Horror|Thriller', 'A horror-thriller about a deadly game of survival in a remote location.'),
(69, 'Drive Thru', 'Comedy|Horror', 'A horror-comedy set in a fast-food restaurant with a murderous mascot.'),
(70, 'Lady Chatterley''s Lover', 'Drama|Romance', 'A romantic drama about an aristocratic woman''s affair with a gamekeeper.'),
(71, 'Malice', 'Thriller', 'A suspenseful thriller about a woman entangled in a web of deceit and danger.'),
(72, 'Prime of Miss Jean Brodie, The', 'Drama', 'A drama about an unconventional teacher influencing her young students.'),
(73, 'The Emperor''s Club', 'Drama', 'A thought-provoking drama about an inspiring teacher and his students.'),
(74, 'Lost Patrol, The', 'Adventure|Drama|War', 'A war drama about a British patrol lost in the Mesopotamian desert.'),
(75, 'Quatsch und die Nasenbärbande', 'Children', 'A children''s adventure about a group of kids and a mischievous raccoon.'),
(76, 'Swell Season, The', 'Documentary|Romance', 'A documentary about the romance and music of a folk duo.'),
(77, 'Funeral Parade of Roses (Bara no sôretsu)', 'Drama', 'An avant-garde drama exploring the underground scene in Tokyo.'),
(78, 'Bigamist, The', 'Drama', 'A drama about a man leading a double life with two families.'),
(79, 'Banklady', 'Action|Crime|Drama|Romance', 'A romantic drama about Germany''s first female bank robber.'),
(80, 'Transamerica', 'Adventure|Comedy|Drama', 'A road-trip adventure about a trans woman discovering her long-lost son.'),
(81, 'Last Days of Pompeii, The', 'Adventure|Drama', 'A historical drama set in the final days before the eruption of Mount Vesuvius.'),
(82, 'Gone Baby Gone', 'Crime|Drama|Mystery', 'A crime drama about two detectives investigating a child''s abduction.'),
(83, 'Nobody Knows Anybody (Nadie conoce a nadie)', 'Romance|Thriller', 'A thriller about a writer entangled in a dangerous game in Seville.'),
(84, 'Selfish Giant, The', 'Drama', 'A powerful drama about two boys'' friendship in a tough neighborhood.'),
(85, 'Blossoms in the Dust', 'Drama', 'A historical drama about a woman''s fight against child exploitation.'),
(86, 'Raincoat', 'Drama|Romance', 'A romantic drama about former lovers reuniting on a rainy day.'),
(87, 'Dark Corner, The', 'Crime|Drama|Film-Noir', 'A classic film-noir involving a private detective in a web of deceit.'),
(88, 'Walk in the Sun, A', 'War', 'A war movie depicting the experiences of American infantrymen in Italy.'),
(89, 'One Step Ahead of My Shadow', '(no genres listed)', 'A mysterious tale where details are as elusive as a shadow.'),
(90, 'Arthur and the Invisibles', 'Action|Children|Fantasy', 'A children''s fantasy adventure in a magical miniature world.'),
(91, 'Jumbo (Billy Rose''s Jumbo)', 'Comedy|Musical|Romance', 'A musical romance set in the vibrant backdrop of a circus.'),
(92, 'Mothman Prophecies, The', 'Drama|Fantasy|Horror|Mystery|Thriller', 'A supernatural thriller about a journalist investigating strange occurrences.'),
(93, 'While She Was Out', 'Thriller', 'A suspenseful thriller about a woman fighting for survival in a dangerous night.'),
(94, 'Escape Me Never', 'Drama', 'A poignant drama about love and loyalty set against a challenging backdrop.'),
(95, 'Looking for Richard', 'Documentary|Drama', 'A documentary exploring the complexities of staging a Shakespearean play.'),
(96, 'Bachelor Party Vegas', 'Adventure|Comedy', 'A wild comedy about a bachelor party that takes unexpected turns in Vegas.'),
(97, 'Pact, The', 'Horror|Mystery|Thriller', 'A chilling horror where a pact leads to mysterious and terrifying events.'),
(98, 'Waiting to Exhale', 'Comedy|Drama|Romance', 'A heartwarming tale of friendship and love challenges among a group of women.'),
(99, 'No Greater Love', 'Drama|Romance', 'A romantic drama exploring the depths and sacrifices of true love.'),
(100, 'Hidden Agenda', 'Drama|Thriller', 'A political thriller uncovering a conspiracy with unexpected twists.'),
(101, 'Dance Party, USA', 'Drama', 'A coming-of-age drama set against the backdrop of a dance party.'),
(102, 'Simone (S1m0ne)', 'Comedy|Drama|Fantasy|Sci-Fi', 'A satirical sci-fi about a director who digitally creates an actress.'),
(103, 'In a Year with 13 Moons (In einem Jahr mit 13 Monden)', 'Drama', 'An emotional journey of a transgender woman navigating life''s challenges.'),
(104, 'Accidental Spy, The (Dak miu mai shing)', 'Action|Comedy|Thriller', 'An action-comedy about an ordinary man unwittingly caught in a spy game.'),
(105, 'Chinaman (Kinamand)', 'Drama', 'A drama about cultural encounters and unexpected connections.'),
(106, 'This Is Not a Film (In film nist)', 'Documentary', 'A unique documentary capturing the life of a filmmaker under house arrest.'),
(107, 'Colorado Territory', 'Western', 'A classic Western tale of outlaws and heists in the Colorado wilderness.'),
(108, 'Pumpkin', 'Comedy|Drama|Romance', 'A quirky romantic comedy about an unconventional love story.'),
(109, 'Knucklehead', 'Comedy|Drama', 'A heartwarming comedy-drama about an underdog facing life''s challenges.'),
(110, 'The Shadow of the Eagle', 'Crime|Drama|Mystery|Thriller', 'A gripping thriller involving crime, mystery, and dark secrets.'),
(111, 'Fall Time', 'Drama', 'A drama about friends who get entangled in a dangerous situation during fall.'),
(112, 'Magadheera', 'Action|Adventure|Fantasy|Romance', 'An epic tale of romance and adventure in a fantastical world.'),
(113, 'Stunt Squad', 'Action|Crime|Thriller', 'An action-packed crime thriller about a special squad taking on dangerous criminals.'),
(114, 'Lie with Me', 'Drama|Romance', 'An intense romantic drama exploring the dynamics of a passionate relationship.'),
(115, 'Whitewash', 'Drama', 'A drama about personal struggles and redemption in a snowy, isolated setting.'),
(116, 'Storyville', 'Drama|Thriller', 'A thriller set in Storyville, where secrets and mysteries unfold.'),
(117, 'Casa de los babys', 'Drama', 'A drama about the emotional journeys of women waiting to adopt babies.'),
(118, 'C.S.A.: The Confederate States of America', 'Comedy|Drama', 'A satirical comedy presenting an alternate history where the Confederacy won.'),
(119, 'Blind Fury', 'Action|Thriller', 'An action-packed thriller about a blind swordsman on a vengeful mission.'),
(120, 'Thing Called Love, The', 'Comedy|Drama|Romance', 'A romantic comedy about aspiring musicians chasing their dreams.'),
(121, 'Porgy and Bess', 'Drama|Musical|Romance', 'A classic musical romance set in the vibrant community of Catfish Row.'),
(122, 'Handsome Harry', 'Crime|Drama', 'A crime drama about a man confronting his past and a mysterious crime.'),
(123, 'Tales from the Crypt Presents: Demon Knight', 'Horror|Thriller', 'A horror-thriller about a battle between good and evil over a powerful relic.'),
(124, 'Johns', 'Drama', 'A gritty drama about the lives of male escorts on the streets.'),
(125, 'Richard Pryor: Live in Concert', 'Comedy|Documentary', 'A hilarious and groundbreaking stand-up performance by Richard Pryor.'),
(126, 'Midnight Movies: From the Margin to the Mainstream', 'Documentary', 'A documentary exploring the phenomenon of cult films and midnight movie screenings.'),
(127, 'Rebecca', 'Drama|Mystery|Romance|Thriller', 'A suspenseful tale of romance and mystery at the Manderley estate.'),
(128, 'Fade to Black', 'Documentary', 'A documentary chronicling the life and career of a renowned entertainer.'),
(129, 'Last Drop, The', 'Action|Adventure|Crime|War', 'An action-packed adventure set during a war, involving a daring heist.'),
(130, 'Fun and Fancy Free', 'Animation|Children|Musical', 'A lighthearted animated musical perfect for children.'),
(131, 'Edge, The (Kray)', 'Adventure|Drama|Romance', 'An adventure-drama about survival and romance in the wilderness.'),
(132, 'Lathe of Heaven', 'Sci-Fi', 'A sci-fi story about a man whose dreams can alter reality.'),
(133, 'Jack and the Cuckoo-Clock Heart (Jack et la mécanique du coeur)', 'Adventure|Animation|Drama|Fantasy|Musical|Romance', 'An animated fantasy about a boy with a cuckoo-clock heart on an adventurous quest.'),
(134, 'Girl with the Dragon Tattoo, The (Män som hatar kvinnor)', 'Crime|Drama|Mystery|Thriller', 'A gripping thriller about a journalist and a hacker uncovering family secrets.'),
(135, 'Marie Antoinette', 'Drama|Romance', 'A lavish drama about the life of the infamous Queen Marie Antoinette.'),
(136, 'Stonewall Uprising', 'Documentary', 'A powerful documentary about the pivotal event in LGBTQ+ rights history.'),
(137, '99 River Street', 'Action|Crime|Drama|Film-Noir', 'A film-noir action-drama about an ex-boxer caught in a web of crime.'),
(138, 'Good Old Fashioned Orgy, A', 'Comedy', 'A raucous comedy about a group of friends planning an elaborate orgy.'),
(139, 'Marlene Dietrich: Shadow and Light', 'Documentary', 'A documentary exploring the life and career of the iconic Marlene Dietrich.'),
(140, 'Welcome to the Rileys', 'Drama', 'A drama about a grieving couple finding solace in helping a young woman.'),
(141, 'Run for Cover', 'Western', 'A Western about a man wrongly accused of bank robbery seeking justice.'),
(142, 'All the Light in the Sky', 'Drama', 'A drama about an aging actress reflecting on her life and career.'),
(143, 'Be Cool', 'Comedy|Crime|Musical', 'A comedy about the music industry, filled with crime and amusing misadventures.'),
(144, 'Jesse Stone: Night Passage', 'Crime|Drama|Mystery', 'A crime drama about a small-town police chief solving a mysterious case.'),
(145, '20 Feet from Stardom', 'Documentary', 'A documentary spotlighting the talented backup singers behind major music stars.'),
(146, 'Dreamcatcher', 'Drama|Horror|Sci-Fi|Thriller', 'A sci-fi thriller about friends facing an alien invasion in a winter cabin.'),
(147, 'At Close Range', 'Crime|Drama', 'A drama about a young man drawn into his family''s criminal activities.'),
(148, 'Damsels in Distress', 'Comedy|Romance', 'A comedy about a group of women navigating college and romantic entanglements.'),
(149, 'Phenomenon', 'Drama|Romance', 'A touching drama about a man who develops extraordinary abilities.'),
(150, 'Goodbye Again', 'Drama|Romance', 'A romantic drama about the complexities of love and relationships.')